name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@digidocs-org"
      - name: Setup git user
        run: |
          git config --global user.name ${{secrets.USER_GITHUB}}
          git config --global user.email ${{secrets.USER_EMAIL}}
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: Build the project
        run: yarn build
      - name: Release
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
